# Generated by Django 3.0.2 on 2020-01-25 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('example', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='tax_rate',
            field=models.IntegerField(default=0),
        ),
    ]
